name: Deploy SimpleWhale (LAN)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Docker Compose Down
        run: docker compose down
        working-directory: ${{ github.workspace }}

      - name: Docker Compose Up
        run: docker compose up -d
        working-directory: ${{ github.workspace }}
        